# Generated by Django 4.1.6 on 2023-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_email', models.CharField(default='', max_length=100)),
                ('book_date', models.CharField(max_length=20)),
                ('book_time', models.TimeField()),
                ('people', models.IntegerField(default='0')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('des_price', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='./menu')),
            ],
        ),
    ]
