# Generated by Django 4.1.6 on 2023-04-02 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0002_alter_book_book_time_alter_book_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
