# Generated by Django 4.1.6 on 2023-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0003_book_book_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_subject', models.CharField(max_length=200)),
                ('contact_message', models.CharField(max_length=2000)),
            ],
        ),
    ]
