# Generated by Django 4.1.6 on 2023-04-02 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
